/* tslint:disable */
/* eslint-disable */
/**
 * wiki-quiz-api-spec
 * [QuizWiki](https://www.quiz-wiki.com/)のAPI仕様書です。
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

